openapi: 3.0.2
info:
  title: UNB Earth Sciences Collection API
  description: The UNB Eartch Science Collection provides access to specimen metadata curated by the UNB Eartch Science Centre.
  version: '0.1'

servers:
  - url: http://local-unbgeology.lib.unb.ca:3118/api

paths:
  /classifications:
    get:
      responses:
        200:
          description: Successfully retrieved category objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: "#/components/schemas/Classification"
                    - type: object
                      properties:
                        super:
                          type: array
                          items:
                            $ref: "#/components/schemas/Classification"
                          example:
                            - name: Rock
                              slug: rock
                            - name: Igneous Rock
                              slug: igneous-rock

        204:
          description: No classification objects found.
        406:
          description: Requested format not supported.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Server error.
    post:
      security:
        - Session: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Classification"
                - type: object
                  properties:
                    super:
                      type: string
                      description: Name or slug of an existing classification.
                      example: "igneous-rock"
      responses:
        201:
          description: Successfully created classification object.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Classification"
                  - type: object
                    properties:
                      super:
                        type: array
                        items:
                          $ref: "#/components/schemas/Classification"
                        example:
                          - name: Rock
                            slug: rock
                          - name: Igneous Rock
                            slug: igneous-rock
        # 202:
        #   description: Accepted batch.
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Authentication required to create specimen object.
        403:
          description: Permission required to create specimen object.
        500:
          description: Server error.

  /classifications/{slug}:
    get:
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          example: quartz-diorite
      responses:
        200:
          description: Successfully retrieved classification object.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Classification"
                  - type: object
                    properties:
                      super:
                        type: array
                        items:
                          $ref: "#/components/schemas/Classification"
                        example:
                          - name: Rock
                            slug: rock
                          - name: Igneous Rock
                            slug: 'igneous-rock'
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Classification object not found.
        500:
          description: Server error.

    put:
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          example: quartz-diorite
      security:
        - Session: []
      
      responses:
        200:
          description: Successfully updated classification object.
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      name:
                        type: string
                  - type: object
                    properties:
                      slug:
                        type: string
                  - type: object
                    properties:
                      super:
                        type: array
                        items:
                          $ref: "#/components/schemas/Classification"
                example:
                  name: Quartz monzonite
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Classification object not found.
        401:
          description: Authentication required to update classification object.
        403:
          description: Permission required to update classification object.
        500:
          description: Server error.

    delete:
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
          example: quartz-diorite
      security:
        - Session: []
      
      responses:
        204:
          description: Classification object deleted.
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Classification object not found.
        401:
          description: Authentication required to update classification object.
        403:
          description: Permission required to update classification object.
        500:
          description: Server error.


  /specimens:
    get:
      parameters:
        - name: start
          in: query
          schema:
            type: number
            minimum: 1
            default: 1
        - name: count
          in: query
          schema:
            type: number
            minimum: 1
            maximum: 500
            default: 50
      responses:
        200:
          description: Successfully retrieved specimen objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Specimen"
        204:
          description: No specimen objects found.
        406:
          description: Requested format not supported.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Server error.

    post:
      security:
        - Session: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Specimen"
      responses:
        201:
          description: Successfully created specimen object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Specimen"
        # 202:
        #   description: Accepted batch.
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Authentication required to create specimen object.
        403:
          description: Permission required to create specimen object.
        500:
          description: Server error.

  /specimens/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: UNB-001
        - name: only
          in: query
          schema:
            type: array
            items:
              type: string
          example: name,description
      responses:
        200:
          description: Successfully retrieved specimen object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Specimen"
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Specimen object not found.
        401:
          description: Authentication required to retrieve specimen object.
        403:
          description: Permission required to retrieve specimen object.
        500:
          description: Server error.
    
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: UNB-001
      security:
        - Session: []
      
      responses:
        200:
          description: Successfully updated specimen object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Specimen"
        400:
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Specimen object not found.
        401:
          description: Authentication required to update specimen object.
        403:
          description: Permission required to update specimen object.
        500:
          description: Server error.
                  
components:
  schemas:
    Classification:
      type: object
      required:
        - name
        - slug
      properties:
        name:
          type: string
          example: Quartz diorite
        slug:
          type: string
          example: quartz-diorite

    Specimen:
      type: object
      required:
        - name
        - id
      properties:
        id:
          type: string
          example: UNB-001
        name:
          type: string
          example: Metaconglomerate
        description:
          type: string
          format: md
          maxLength: 1000
          example: __*Metaconglomerate*__ is a rock type which originated from conglomerate after undergoing metamorphism.
        dimension:
          type: object
          properties:
            width:
              type: number
              title: Width in millimetre.
              minimum: 0
              example: 29
            length:
              type: number
              title: Length in millimetre.
              minimum: 0
              example: 78
        date:
          type: string
          format: date
          example: 100 Million Years
        age:
          type: string
          example: pre-Cambrian
        origin:
          type: object
          required:
            - latitude
            - longitude
          properties:
            latitude:
              type: number
              description: Latitude in Decimal Degrees.
              minimum: -90
              maximum: 90
              example: 45.54654574420113
            longitude:
              type: number
              description: Longitude in Decimal Degrees.
              minimum: -180
              maximum: 180
              example: -65.01963261586597
            accuracy:
              type: number
              description: Accuracy of the location in metres.
              minimum: 0
              default: 0
              example: 50
            name:
              type: string
              description: Resolved geographical location name.
              example: Point Wolfe, Fundy National Park, New Brunswick, Canada
            description:
              type: string
              description: Additional location details, e.g. name of rock formation.
              example: The Hopewell Conglomerate
        pieces:
          type: number
          minimum: 1
          default: 1
          example: 1
        partial:
          type: boolean
          default: false
        composition:
          type: string
          example: Granitic
        status:
          type: string
          enum:
            - draft
            - review
            - published
          readOnly: true
          default: draft
        created:
          type: number
          description: UNIX timestamp of record's creation.
          readOnly: true
          example: 1687276202
        modified:
          type: number
          description: UNIX timestamp of records's most recent modification.
          readOnly: true
          example: 1687276202


    Error:
      type: object
      properties:
        errorDetails:
          type: string

  securitySchemes:
    Session:
      type: apiKey
      in: cookie
      name: sessionId